# Use an official Ubuntu 18.04 as a parent image
FROM ubuntu:18.04

# Update Ubuntu
RUN apt-get update -y

# Install Python3
RUN apt-get install -y python3

# Install Pip3
RUN apt-get install -y python3-pip
